Add tests for xyz.chunkstories.util.math.HeightmapMesher.java
Diffblue-benchmarks/chunkstories pull request #1
Opened 2019-04-02 10:41 UTC by James-Adam

PR text incoming

2019-04-02 10:42 UTC, JohnLBergqvist requested changes

2019-04-02 10:42 UTC, JohnBergqvist commented on common/src/test/java/xyz/chunkstories/util/math/HeightmapMesherTest.java
> +}
New line.

2019-04-02 10:42 UTC, JohnBergqvist commented on common/src/test/java/xyz/chunkstories/util/math/HeightmapMesherTest.java
> +        assertNull(heightMap.nextSurface());
Personally i'd remove the blank line above at least the `heighMap.n` line.

2019-04-02 11:20 UTC, petersear approved these changes
Just a couple of suggestions to "condense the space". Fine as it is though.

2019-04-02 11:20 UTC, petersear commented on common/src/test/java/xyz/chunkstories/util/math/HeightmapMesherTest.java
> +
Condense the space?

2019-04-02 11:20 UTC, petersear commented on common/src/test/java/xyz/chunkstories/util/math/HeightmapMesherTest.java
> +
Remove empty line?

2019-04-02 12:12 UTC, JohnLBergqvist approved these changes

2019-04-04 08:10 UTC, peterschrammel approved these changes

2019-04-04 08:10 UTC, peterschrammel commented on common/src/test/java/xyz/chunkstories/util/math/HeightmapMesherTest.java
> +        final HeightmapMesher heightMap = new HeightmapMesher( map, id_list, 1, 3, 1, 1, 500);
```suggestion
        final HeightmapMesher heightMap = new HeightmapMesher(map, id_list, 1, 3, 1, 1, 500);
```

2019-04-04 10:14 UTC, closed without merging